name: website
description: My personal website

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_shaders: ^0.1.2
  flutter_animate: ^4.2.0+1
  provider: ^6.0.5
  url_launcher: ^6.1.14
  html: ^0.15.4
  video_player: ^2.7.2
  crypto: ^3.0.3
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - 'assets/resume.pdf'
    - 'assets/github-invertocat-logo.png'
    - 'assets/devpost-logo.png'
    - 'assets/showcase-media/sportvue/light/calendar-light.png'
    - 'assets/showcase-media/sportvue/light/dashboard-light.png'
    - 'assets/showcase-media/sportvue/light/data-import-light.mp4'
    - 'assets/showcase-media/sportvue/light/login-light.png'
    - 'assets/showcase-media/sportvue/light/no-data-light.png'
    - 'assets/showcase-media/sportvue/light/profile-light.png'
    - 'assets/showcase-media/sportvue/light/session-data-light.png'
    - 'assets/showcase-media/sportvue/light/trends-light.png'
    - 'assets/showcase-media/sportvue/dark/calendar-dark.png'
    - 'assets/showcase-media/sportvue/dark/dashboard-dark.png'
    - 'assets/showcase-media/sportvue/dark/data-import-dark.mp4'
    - 'assets/showcase-media/sportvue/dark/login-dark.png'
    - 'assets/showcase-media/sportvue/dark/no-data-dark.png'
    - 'assets/showcase-media/sportvue/dark/profile-dark.png'
    - 'assets/showcase-media/sportvue/dark/session-data-dark.png'
    - 'assets/showcase-media/sportvue/dark/trends-dark.png'
    - 'assets/showcase-media/layover-party/images/onboarding-one.png'
    - 'assets/showcase-media/layover-party/images/onboarding-two.png'
    - 'assets/showcase-media/layover-party/images/onboarding-three.png'
    - 'assets/showcase-media/layover-party/images/search-bar.png'
    - 'assets/showcase-media/layover-party/images/trip-ticket.png'
    - 'assets/showcase-media/layover-party/images/trips.png'
    - 'assets/showcase-media/layover-party/videos/onboarding-first-second.mp4'
    - 'assets/showcase-media/layover-party/videos/onboarding-second-third.mp4'
    - 'assets/showcase-media/layover-party/videos/search-bar.mp4'
    - 'assets/showcase-media/layover-party/videos/trip-ticket.mp4'
    - 'assets/showcase-media/allynd/login.png'
    - 'assets/showcase-media/allynd/onboarding-one.png'
    - 'assets/showcase-media/allynd/onboarding-two.png'
    - 'assets/showcase-media/allynd/onboarding-three.png'

  fonts:
    - family: Inter
      fonts:
        - asset: 'assets/fonts/inter/Inter-Thin.ttf'
          weight: 100
        - asset: 'assets/fonts/inter/Inter-ExtraLight.ttf'
          weight: 200
        - asset: 'assets/fonts/inter/Inter-Light.ttf'
          weight: 300
        - asset: 'assets/fonts/inter/Inter-Regular.ttf'
          weight: 400
        - asset: 'assets/fonts/inter/Inter-Medium.ttf'
          weight: 500
        - asset: 'assets/fonts/inter/Inter-SemiBold.ttf'
          weight: 600
        - asset: 'assets/fonts/inter/Inter-Bold.ttf'
          weight: 700
        - asset: 'assets/fonts/inter/Inter-ExtraBold.ttf'
          weight: 800
        - asset: 'assets/fonts/inter/Inter-Black.ttf'
          weight: 900
    - family: Libre Baskerville
      fonts:
        - asset: 'assets/fonts/libre-baskerville/LibreBaskerville-Regular.ttf'
        - asset: 'assets/fonts/libre-baskerville/LibreBaskerville-Bold.ttf'
          weight: 700
        - asset: 'assets/fonts/libre-baskerville/LibreBaskerville-Italic.ttf'
          style: italic

  shaders:
    - 'assets/shaders/gradient.frag'
