name: website
description: My personal website

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_shaders: ^0.1.2
  flutter_animate: ^4.2.0+1
  provider: ^6.0.5
  url_launcher: ^6.1.14
  html: ^0.15.4
  video_player: ^2.7.2
  crypto: ^3.0.3
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - 'assets/resume.pdf'
    - 'assets/github-invertocat-logo.png'
    - 'assets/devpost-logo.png'
    - 'assets/shadertoy-logo.png'

    # SportVue light
    - 'assets/showcase-media/sportvue/light/calendar-light.jpg'
    - 'assets/showcase-media/sportvue/light/dashboard-light.jpg'
    - 'assets/showcase-media/sportvue/light/login-light.jpg'
    - 'assets/showcase-media/sportvue/light/no-data-light.jpg'
    - 'assets/showcase-media/sportvue/light/profile-light.jpg'
    - 'assets/showcase-media/sportvue/light/session-data-light.jpg'
    - 'assets/showcase-media/sportvue/light/trends-light.jpg'

    # SportVue dark
    - 'assets/showcase-media/sportvue/dark/calendar-dark.jpg'
    - 'assets/showcase-media/sportvue/dark/dashboard-dark.jpg'
    - 'assets/showcase-media/sportvue/dark/login-dark.jpg'
    - 'assets/showcase-media/sportvue/dark/no-data-dark.jpg'
    - 'assets/showcase-media/sportvue/dark/profile-dark.jpg'
    - 'assets/showcase-media/sportvue/dark/session-data-dark.jpg'
    - 'assets/showcase-media/sportvue/dark/trends-dark.jpg'

    # Layover Party
    - 'assets/showcase-media/layover-party/onboarding-one.jpg'
    - 'assets/showcase-media/layover-party/onboarding-two.jpg'
    - 'assets/showcase-media/layover-party/onboarding-three.jpg'
    - 'assets/showcase-media/layover-party/search-bar.jpg'
    - 'assets/showcase-media/layover-party/trip-ticket.jpg'
    - 'assets/showcase-media/layover-party/trips.jpg'

    # Dragonator light
    - 'assets/showcase-media/dragonator/light/create-paddler-light.jpg'
    - 'assets/showcase-media/dragonator/light/roster-light.jpg'
    - 'assets/showcase-media/dragonator/light/edit-lineup-light.jpg'
    - 'assets/showcase-media/dragonator/light/paddler-details-light.jpg'
    - 'assets/showcase-media/dragonator/light/settings-light.jpg'

    # Dragonator dark
    - 'assets/showcase-media/dragonator/dark/create-paddler-dark.jpg'
    - 'assets/showcase-media/dragonator/dark/roster-dark.jpg'
    - 'assets/showcase-media/dragonator/dark/edit-lineup-dark.jpg'
    - 'assets/showcase-media/dragonator/dark/paddler-details-dark.jpg'
    - 'assets/showcase-media/dragonator/dark/settings-dark.jpg'

    # Allynd
    - 'assets/showcase-media/allynd/login.jpg'
    - 'assets/showcase-media/allynd/onboarding-one.jpg'
    - 'assets/showcase-media/allynd/onboarding-two.jpg'
    - 'assets/showcase-media/allynd/onboarding-three.jpg'

  fonts:
    - family: Inter
      fonts:
        - asset: 'assets/fonts/inter/Inter-Thin.ttf'
          weight: 100
        - asset: 'assets/fonts/inter/Inter-ExtraLight.ttf'
          weight: 200
        - asset: 'assets/fonts/inter/Inter-Light.ttf'
          weight: 300
        - asset: 'assets/fonts/inter/Inter-Regular.ttf'
          weight: 400
        - asset: 'assets/fonts/inter/Inter-Medium.ttf'
          weight: 500
        - asset: 'assets/fonts/inter/Inter-SemiBold.ttf'
          weight: 600
        - asset: 'assets/fonts/inter/Inter-Bold.ttf'
          weight: 700
        - asset: 'assets/fonts/inter/Inter-ExtraBold.ttf'
          weight: 800
        - asset: 'assets/fonts/inter/Inter-Black.ttf'
          weight: 900
    - family: Libre Baskerville
      fonts:
        - asset: 'assets/fonts/libre-baskerville/LibreBaskerville-Regular.ttf'
        - asset: 'assets/fonts/libre-baskerville/LibreBaskerville-Bold.ttf'
          weight: 700
        - asset: 'assets/fonts/libre-baskerville/LibreBaskerville-Italic.ttf'
          style: italic

  shaders:
    - 'assets/shaders/gradient.frag'
